### ISSUE TITLE
Claude 3 and latest OpenAI

### ISSUE THREAD

**Issue by AdrianSimionov** [GPT-Fathom/GPT-Fathom#11]
Any plans on adding Claude 3 models results? Same question for GPT-4 Turbo 0125.

Do we have an estimated number of tokens usage per set of tests? My only concern about running my own tests was that I do not know how much it would cost.

**Comment by shenz2-2000** [comment]
Hi!

Sorry for the delayed reply. The total cost for executing the primary settings will be 7,200 million tokens (as input tokens), and you can estimate the cost accordingly. If you need further token information for a specific dataset, please let me know.

As for now, unfortunately we don't have the plan for Claude 3 and GPT-4 turbo. We would greatly appreciate your contribution of any results if you have conducted the tests.
