### ISSUE TITLE
Legacy completion function for gpt-4

### ISSUE THREAD

**Issue by QiTianyu-0403** [GPT-Fathom/GPT-Fathom#12]
I am considering using it to conduct some assessments for my individual work. At the moment, the resources I have at my disposal include the APIs for Azure's gpt-35-turbo and gpt4-turbo. Upon reviewing your Readme, I noticed that it mentioned the requirement of having a completion function (the code used the legacy completion) when testing using the “oaieval” command. I did my own research and found that the current API for GPT-4 lacks the legacy completion function. However, I have observed that your test results did include details pertaining to GPT-4. I was wondering how you managed to achieve this.

Could you kindly guide me on this matter? Your support and guidance would be highly appreciated.

**Comment by shenz2-2000** [comment]
Hi Tianyu,
 
For chat models like GPT4 and GPT3.5, we use Chat Completion and for text model like text-davinci-003, we use the text completion. Details of this text to chat transition can be found here: https://github.com/GPT-Fathom/GPT-Fathom/blob/main/evals/prompt/base.py
 
Hope this answers your questions.
