### ISSUE TITLE
Question about temperature

### ISSUE THREAD

**Issue by imoneoi** [GPT-Fathom/GPT-Fathom#2]
Is it appropriate to set all sampling temperatures to the same (such as `0.8`) for all models? Different models may produce different logit scales (or "confidence"), so it may prefer the model that fits that temperature. Most benchmarks use temperature `0` (or greedy decoding), which is not affected by the logit scale.

**Comment by shenz2-2000** [comment]
Hi @imoneoi , thanks for your question. 

In our benchmarks, we set the temperature `T=0.0` for all tasks except the coding benchmarks, such as humaneval and mbpp. For coding benchmarks, we require sampling to calculate the pass@k score, which necessitates a higher temperature setting. We aligned our setting with previous works Codex (https://arxiv.org/abs/2107.03374), Palm2 (https://arxiv.org/abs/2305.10403), and Llama (https://arxiv.org/abs/2302.13971), opting for a temperature of T=0.8.

We also have explored the impact of temperature in our paper in Section 3.2 (Sampling Variance) and Appendix D of our paper. You could check these for more details.
