### ISSUE TITLE
How to evaluate llama1,2 on all tasks listed in GPT-Fathom/evals/registry/data?

### ISSUE THREAD

**Issue by YingHH1** [GPT-Fathom/GPT-Fathom#6]
Is there an option to evaluate the model on all available benchmark tests?

**Comment by shenz2-2000** [comment]
Hi @YingHH1, to evaluate llama on all the benchmark, you can simply run `oaievalset llama whole-set --eval_in_batch True` or `oaievalset llama2 whole-set --eval_in_batch True`. (`git pull` first to make sure you're using our latest version) 
Remember to modify the path to model checkpoint in:
For llama: https://github.com/GPT-Fathom/GPT-Fathom/blob/82e1356ec403e4d6b40fd418cd10e2b251f2001c/evals/completion_fns/llama.py#L41
or for llama2: https://github.com/GPT-Fathom/GPT-Fathom/blob/82e1356ec403e4d6b40fd418cd10e2b251f2001c/evals/completion_fns/llama.py#L130 You can also modify the batch size and parallelism method here.

**Comment by YingHH1** [comment]
Thank you!
